name : First WorkFlow
on : [pull_request,push]
jobs: 
    run-shell-commands: 
        runs-on: ubuntu-latest
        environment: test
        steps: 
             
            - name : "envvariablevalue"
              run: echo $MY_SECRET_ENV_VAR
              env:
                MY_SECRET_ENV_VAR: echo ${{ env.MY_SECRET_ENV_VAR.TEST_VARIABLE}}
