name : First WorkFlow
on : [pull_request,push]
env: 
  relase : "releaseDire"
jobs: 
    run-shell-commands: 
        runs-on: ubuntu-latest
        environment: test
        steps: 
             
            - name : "envvariablevalue"
              run: |
               echo ${{vars.TEST_VARIABLE}}
               echo ${{env.relase}}
               echo ${{secrets.TEST_SECRET}}
               echo ${{github.event_name}}
