name : First WorkFlow
on : [pull_request,push]
jobs: 
    run-shell-commands: 
        runs-on: ubuntu-latest
        steps: 
            - name : echo  a string
              run : echo "hello world testingasdf "
                

