name : First WorkFlow
on : [pull_request,push]
jobs: 
    run-shell-commands: 
        runs-on: ubuntu-latest
        environment: test
        steps: 
            - name : echo  a string
              run : echo "hello world testingasdf "

            - name : "error checking"
              run : 'echo "::error:: Missing semicolon"'

            - name : "debug checking"
              run : 'echo "::debug:: Missing semicolon"'

            - name : "warning checking"
              run : 'echo "::warning:: Missing semicolon"'
              
            - name : "notice checking"
              run : 'echo "::notice:: Missing semicolon"'

            - name : "envvariablevalue"
              run: echo $MY_SECRET_ENV_VAR
              env:
                MY_SECRET_ENV_VAR: echo ${{ env.MY_SECRET_ENV_VAR.TEST_VARIABLE}}
