 

name: First WorkFlow-Env-level-workflow
on: [push]

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Set the value
        id: step_one
        run: |
          echo "action_state=yellow" >> "$GITHUB_ENV123"
          echo "action_state2=yellow2222222222" >> "$GITHUB_ENV456"
          echo "action_state3=333333333333333" >> "$GITHUB_ENV456"
      - name: Use the value
        id: step_two
        run: |
          printf '%s\n' "$action_state" # This will output 'yellow'
           printf '%s\n' "$action_state2" 
           echo "$action_state3"
           echo  $GITHUB_REF  
        

# name : First WorkFlow
# on : [pull_request,push]
# run-name: "Expression @${{github.actor}}   @${{github.event_name}}"
# env: 
#   release : "releaseDire"
  
# jobs: 
    
#     run-shell-commands: 
#         if : github.event_name != 'push'
#         runs-on: ubuntu-latest
#         environment: test
       
#         steps: 
             
#             - name : "envvariablevalue"
#               run: |
#                echo ${{vars.TEST_VARIABLE}}
#                echo ${{env.release}}
#                echo ${{secrets.TEST_SECRET}}
#                echo ${{github.event_name}}
#                echo 'test'


                # $GITHUB_REF    vs '${{github_ref}}' 



# name: CI Workflow
# on: [push]

# jobs:
#   build:
#     runs-on: ubuntu-latest #self-hosted  # Uses any available self-hosted runner
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#       - name: Run a build script
#         run: ./build.sh
