# name : First WorkFlow
# on : [pull_request,push]
# run-name: "Expression @${{github.actor}}   @${{github.event_name}}"
# env: 
#   release : "releaseDire"
  
# jobs: 
    
#     run-shell-commands: 
#         if : github.event_name != 'push'
#         runs-on: ubuntu-latest
#         environment: test
       
#         steps: 
             
#             - name : "envvariablevalue"
#               run: |
#                echo ${{vars.TEST_VARIABLE}}
#                echo ${{env.release}}
#                echo ${{secrets.TEST_SECRET}}
#                echo ${{github.event_name}}
#                echo 'test'



name: CI Workflow
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest #self-hosted  # Uses any available self-hosted runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run a build script
        run: ./build.sh
