name: File Change Trigger

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Perform your action
      run: echo "Changes detected in Test.txt!"
