name: File Change Trigger

on:
  push:
    paths:
      - 'Test.txt'  # Use relative path and forward slashes
      # - 'path/to/your/file/or/directory/**'  # Example of monitoring a directory

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Perform your action
      run: echo "Changes detected in Test.txt!"
